-- CUSTOMER SHOPPING BEHAVIOR ANALYSIS

USE customer_behavior;


-- Q1. What is the total revenue generated by each gender?
SELECT gender, SUM(purchased_amount) AS revenue
FROM customer_shopping_behavior
GROUP BY gender;


-- Q2. Which customers received a discount and spent more than the average purchase amount?
SELECT customer_id, purchased_amount
FROM customer_shopping_behavior
WHERE discount_applied = 'yes'
  AND purchased_amount >= (
      SELECT AVG(purchased_amount) FROM customer_shopping_behavior
  );


-- Q3. What are the top 5 highest-rated products based on average review rating?
SELECT item_purchased, AVG(review_rating) AS "AVERAGE PRODUCT RATING"
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Q4. How does the average purchase amount compare between Standard and Express shipping?
SELECT shipping_type, ROUND(AVG(purchased_amount), 2) AS avg_purchased_amount
FROM customer_shopping_behavior
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. How do subscribers vs non-subscribers compare in terms of customer count, average spend, and total revenue?
SELECT subscription_status,
COUNT(customer_id) AS total_customer,
ROUND(AVG(purchased_amount), 2) AS avg_spend,
ROUND(SUM(purchased_amount), 2) AS total_revenue
FROM customer_shopping_behavior
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;


-- Q6. Which top 5 products have the highest discount application rate?
SELECT item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS discount_rate
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. How many customers fall into each segment: New, Returning, or Loyal (based on previous purchases)?
WITH customer_type AS (
    SELECT customer_id, previous_purchases,
		CASE
			WHEN previous_purchases = 1 THEN 'NEW'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
			ELSE 'Loyal'
           END AS customer_segment
    FROM customer_shopping_behavior
)
SELECT customer_segment, COUNT(*) AS "Number of customer"
FROM customer_type
GROUP BY customer_segment;


-- Q8. Which products are purchased most frequently overall?
SELECT item_purchased, COUNT(*) AS no_of_item_purchased
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY no_of_item_purchased DESC;


-- Q9. What are the top 3 best-selling products within each category?
WITH item_count AS (
    SELECT category, item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_shopping_behavior
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_count
WHERE item_rank <= 3;


-- Q10. Among repeat customers (more than 5 previous purchases), how does subscription status break down?
SELECT subscription_status,
       COUNT(customer_id) AS reapeted_customer
FROM customer_shopping_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q11. Which age group generates the highest total revenue?
SELECT age_group,
       SUM(purchased_amount) AS total_revenue
FROM customer_shopping_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;